server:
  port: 9999

spring:
  application:
    name: java_equity_relay
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://39.107.97.220:1040/lianze_equity_relay?characterEncoding=utf-8
    username: root
    password: Passw0rd
    # 初始化大小，最小，最大
    initial-size: 5
    min-idle: 5
    max-active: 20
    # 配置获取连接等待超时的时间
    max-wait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位毫秒
    time-between-eviction-runs-millis: 60000
    # 配置一个连接在池中最小生存时间
    min-evictable-idle-time-millis: 300000
    validation-query: SELECT 1 FROM bu_sys_user
    test-while-idle: true
    test-on-borrow: false
    test-on-return: false
    # 打开 PSCache，并且指定每个连接上 PSCache 的大小
    pool-prepared-statements: true
    max-pool-prepared-statement-per-connection-size: 20
    # 配置监控统计拦截的 Filter，去掉后监控界面 SQL 无法统计，wall 用于防火墙
    filters: stat,wall,log4j
    # 通过 connection-properties 属性打开 mergeSql 功能；慢 SQL 记录
    connection-properties: druid.stat.mergeSql\=true;druid.stat.slowSqlMillis\=5000

mybatis-plus:
  global-config:
    banner: false
  configuration:
    map-underscore-to-camel-case: true
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.durker.bean
  mapper-locations: classpath:mapper/*.mapper.xml


swagger:
  authorization:
    type: None
  title: 守护权益接龙系统
  description: 系统平台功能，包括首页、接龙、公告、我的等功能。
  version: v1.0
  contact:
    name: 北京蓝英科技有限公司
    email: 312239109@qq.com
  exclude-path: /error/**

file:
  server: https://test.dg.ebfkc.com/relay/
  uploadPath: /website/equity_relay/  #服务器上传路径